@Civir.Auth_HostAddress = http://localhost:5290

GET {{Civir.Auth_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{Civir.Auth_HostAddress}}/weatherforecast/
Accept: application/json

###
